In [1]:
import torch

/home/legion/Documents/LLM/myenv/lib/python3.12/site-packages/torch/_subclasses/functional_tensor.py:368: UserWarning: Failed to initialize NumPy: No module named 'numpy' (Triggered internally at /__w/pytorch/pytorch/torch/csrc/utils/tensor_numpy.cpp:84.)
  cpu = _conversion_method_template(device=torch.device("cpu"))


In [2]:
theta_numerator  = torch.arange(0, 512, 2).float()


In [3]:
theta_numerator

tensor([  0.,   2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
         24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,  46.,
         48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,  68.,  70.,
         72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,  90.,  92.,  94.,
         96.,  98., 100., 102., 104., 106., 108., 110., 112., 114., 116., 118.,
        120., 122., 124., 126., 128., 130., 132., 134., 136., 138., 140., 142.,
        144., 146., 148., 150., 152., 154., 156., 158., 160., 162., 164., 166.,
        168., 170., 172., 174., 176., 178., 180., 182., 184., 186., 188., 190.,
        192., 194., 196., 198., 200., 202., 204., 206., 208., 210., 212., 214.,
        216., 218., 220., 222., 224., 226., 228., 230., 232., 234., 236., 238.,
        240., 242., 244., 246., 248., 250., 252., 254., 256., 258., 260., 262.,
        264., 266., 268., 270., 272., 274., 276., 278., 280., 282., 284., 286.,
        288., 290., 292., 294., 296., 29

In [7]:
theta = 1.0/(theta_numerator **(theta_numerator / 512)).to('cuda')


In [4]:
m= torch.arange(2048, device= 'cuda')


In [5]:
m

tensor([   0,    1,    2,  ..., 2045, 2046, 2047], device='cuda:0')

In [8]:
freqs = torch.outer(m, theta).float()


In [10]:
freqs.shape

torch.Size([2048, 256])

In [11]:
    freqs_complex = torch.polar(torch.ones_like(freqs), freqs)


In [12]:
freqs_complex

tensor([[ 1.0000+0.0000j,  1.0000+0.0000j,  1.0000+0.0000j,  ...,
          1.0000+0.0000j,  1.0000+0.0000j,  1.0000+0.0000j],
        [ 0.5403+0.8415j,  0.5426+0.8400j,  0.5493+0.8356j,  ...,
          1.0000+0.0021j,  1.0000+0.0021j,  1.0000+0.0020j],
        [-0.4161+0.9093j, -0.4112+0.9115j, -0.3965+0.9181j,  ...,
          1.0000+0.0043j,  1.0000+0.0041j,  1.0000+0.0040j],
        ...,
        [-0.9844+0.1759j, -0.8383-0.5453j,  0.9771-0.2127j,  ...,
         -0.3569-0.9341j, -0.4671-0.8842j, -0.5677-0.8232j],
        [-0.6799-0.7333j,  0.0032-1.0000j,  0.7146+0.6996j,  ...,
         -0.3549-0.9349j, -0.4653-0.8852j, -0.5661-0.8244j],
        [ 0.2497-0.9683j,  0.8418-0.5399j, -0.1920+0.9814j,  ...,
         -0.3529-0.9356j, -0.4634-0.8861j, -0.5644-0.8255j]], device='cuda:0')

In [14]:
freqs.shape

torch.Size([2048, 256])

In [16]:
freqs_complex.shape

torch.Size([2048, 256])

In [19]:
a = torch.tensor([1,2,3])
b = torch.tensor([1,2,3])

In [20]:
a*b

tensor([1, 4, 9])

tensor([1, 2, 3])